name: Severyn Kozak
url: https://sevko.io
files_url: /data
description: Severyn Kozak's personal portfolio site and blog.
permalink: /articles/:title
markdown: kramdown
lsi: true
exclude: [Gemfile, Gemfile.lock, CNAME, README.md, publish.sh, Makefile]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed
