name: Severyn Kozak
url: http://sevko.io
files_url: http://files.sevko.io
description: Severyn Kozak's personal portfolio site and blog.
permalink: /articles/:title
markdown: kramdown
lsi: true
exclude: [
  Gemfile, Gemfile.lock, nginx.conf, CNAME, nginx.common.conf, README.md,
  post-receive.sh
]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed
